### ISSUE TITLE
Sourcemap [...] points to missing source files

### ISSUE THREAD

**Issue by sep2** [mathe42/vite-plugin-comlink#30]
Get the following warning when doing `yarn dev`.

> Sourcemap for "comlink@worker:/src/export-result/convert-data.worker.ts" points to missing source files

**Comment by mathe42** [comment]
Can you provide a full reproduktion?

I think other Plugins might interfer. As this Plugin creates no sourcemaps...

**Comment by sep2** [comment]
sure, this is a repro, https://github.com/sep2/comlink-sourcemap-reproduce
tell me if you need further info

**Comment by mathe42** [comment]
I think I understand where the problem comes from and I have currently no idea how to fix it (or if that is even possible).

I think the problem is the following:

comlink:./myWorker.ts => resolved to a new id  => loaded a (mostly) static file => is tranformed by esbuild as it is TypeScript and creates source map pointing to that virtual file => log entry

---
But as this is not that big of a problem (and build and dev work normal just 2 logs) I can not work on that problem. But if you find a solution you can create a PR for that!

**Comment by sep2** [comment]
Sure, thank you for the response. I will close the issue for now.
