### ISSUE TITLE
What is the other plugins to create ComlinkWorker or ComlinkSharedWorker?

### ISSUE THREAD

**Issue by kzq666666** [mathe42/vite-plugin-comlink#74]
Thanks for your awesome plugin.
But I meet with some problems. I use the comlink with 'new Worker()'  except 'ComlinkWorker or ComlinkSharedWorker'. What is the other plugins to create ComlinkWorker or ComlinkSharedWorker?

**Comment by mathe42** [comment]
If you use `new Worker()` and add comlink on your own (with expose, wrap) you don't need this plugin.

I think with your question you mean the sentence in about the plugin order. If you have plugins (that you might wrote on your own) that transform code so that there exists ComlinkWorker or ComlinkSharedWorker or plugins that do some transforms based on ComlinkWorker or ComlinkSharedWorker you have to put those plugins before this plugin. This is to fix #71 where the order of plugins prevented this plugin to work.

**Comment by kzq666666** [comment]
I get it. Thanks for you reply
